name: Automated Security Pipeline

on:
  push:
    branches:
      - developtment/pipeline

jobs:
  Unittest:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Layer Unittest
        run: |
          echo Layer Unittest

  Build:
    needs: Unittest
    runs-on: ubuntu-22.04
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push
        uses: docker/build-push-action@v5.1.0
        with:
          push: false

  Security:
    needs: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Layer Security
        run: |
          echo Layer Security

  Deployment:
    needs: Security
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository # can we remove this?
        uses: actions/checkout@v3

      - name: Setup KubeConfig
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Run kubectl
        run: |
          kubectl delete pod --ignore-not-found=true asp
          kubectl apply -f .github/workflows/asp.yaml
