name: Automated Security Pipeline

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # - name: Build Docker & Push DockerHub
      #   run: |
      #     docker build . --tag ${{ secrets.DOCKER_IMAGE_TAG }}
      #     docker push ${{ secrets.DOCKER_IMAGE_TAG }}

      # - name: Setup KubeConfig
      #   uses: azure/k8s-set-context@v1
      #   with:
      #     kubeconfig: ${{ secrets.KUBE_CONFIG }}

      # - name: Layer Unittest
      # - name: Layer Build
      # - name: Layer Security

      - name: Layer Deployment
        run: |
          echo "Hello World!"
          ls -la
