name: Automated Security Pipeline

on:
  push:
    branches:
      - developtment/pipeline

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup KubeConfig
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Layer Unittest
        run: |
          echo Layer Unittest

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5.1.0
        with:
          push: false

      - name: Layer Security
        run: |
          echo Layer Security

      - name: Layer Deployment
        run: |
          kubectl delete pod --ignore-not-found=true asp
          kubectl apply -f .github/workflows/asp.yaml
